Merge in upstream master @ v0.4.0
vector-im/mautrix-signal pull request #16
Opened 2022-09-22 18:46 UTC by AndrewFerr

v0.4.0 = 90542f770

2022-10-02 11:34 UTC, jaller94 requested changes
The migration isn't working. There's an issue with the filename.

2022-10-02 11:34 UTC, jaller94 commented on mautrix_signal/db/upgrade/__init__.py
> +    v11_puppet_name_quality,
This does not match the filename.

2022-10-02 11:34 UTC, jaller94 commented on mautrix_signal/example-config.yaml
> +    # OpenStreepMap: 'https://www.openstreetmap.org/?mlat={lat}&mlon={long}'
Found two typos and submitted them upstream:
https://github.com/mautrix/signal/pull/311

2022-10-13 14:35 UTC, jaller94 approved these changes
Couldn't find any issues, but I hope we test it on staging first.
It's a big change.

2022-10-18 20:08 UTC, AndrewFerr commented
Should dependencies be locked? Our mautrix-telegram fork locks them: https://github.com/vector-im/mautrix-telegram/blob/element-master/requirements.txt

2022-10-27 05:22 UTC, merged